version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: astroid
    versions:
    - 2.4.2
    - "2.5"
    - 2.5.1
    - 2.5.2
    - 2.5.3
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: pytelegrambotapi
    versions:
    - 3.7.6
  - dependency-name: lazy-object-proxy
    versions:
    - 1.5.2
